name: 'Build'

on:
  push:
  pull_request:

jobs:
  build:
    name: Test build
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn install --immutable

      - name: Build
        run: yarn build

      - name: Prepare build archive
        run: |
          cd dist
          zip -r ../detailed-weather-forecast.zip .

      - name: Verify archive
        run: ls -l

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: detailed-weather-forecast.zip
          path: detailed-weather-forecast.zip
