name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Prepare release
    permissions:
      contents: read
      actions: write
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE_DOWNLOAD_PROMPT: 0
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Check version and tag
        id: version_check
        run: |
          TAG="${GITHUB_REF_NAME}"
          # Removes 'v' or 'v.' at the beginning to get the pure version (e.g. 1.0.0.0 or 1.0.0-beta3)
          VERSION=$(echo "$TAG" | sed -E 's/^v\.?//')

          # Remove everything from '-' onwards for comparison with package.json
          BASE_VERSION="${VERSION%%-*}"

          PKG_VERSION=$(node -p "require('./package.json').version")

          if [ "$PKG_VERSION" != "$BASE_VERSION" ]; then
            echo "Error: The tag base version ($BASE_VERSION) does not match the package.json version ($PKG_VERSION)!"
            exit 1
          fi

          echo "VERSION=$TAG" >> $GITHUB_OUTPUT

          if [[ "$VERSION" == *-* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
            echo "Prerelease detected: $VERSION"
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
            echo "Stable release detected: $VERSION"
          fi

      # Build
      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
          yarn install --immutable

      - name: Build the file
        run: yarn build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_check.outputs.VERSION }}
          files: dist/*
          generate_release_notes: true
          prerelease: ${{ steps.version_check.outputs.IS_PRERELEASE == 'true' }}
