name: Validate

on:
  workflow_run:
    workflows: ['Release']
    types: [completed]

permissions: {}

jobs:
  validate-hacs:
    runs-on: 'ubuntu-latest'
    steps:
      - name: HACS validation
        uses: 'hacs/action@main'
        with:
          category: 'plugin'
